# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Install requirements
      run: |
        pip install -r requirements.txt

    - name: Run lint tests
      run: |
        pip install flake8
        flake8 --ignore=E501 .

    - name: Test with pytest
      run: |
        pip install pytest pytest-azurepipelines pytest-cov
        pytest tests --log-cli-level=DEBUG --doctest-modules --junitxml=junit/test-results.xml --cov=${{ lower(parameters.projectName) }} --cov-report=xml --cov-report=html

    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python updateVersion.py --nextVersion ${{ github.event.release.tag_name }}
        python setup.py sdist bdist_wheel
        twine upload dist/*
